eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      
      
microservice:
  payment-service:
    endpoints:
     endpoint:
      uri: http://PAYMENT-SERVICE/payment/hello
  order-service:
    endpoints:
     endpoint:
      uri: http://ORDER-SERVICE/order/hello
